/*
 * This is free and unencumbered software released into the public domain, following <https://unlicense.org>
 */

package org.ufoss.kotysa.columns

public interface StringFieldColumnNotNull
public interface StringFieldColumnNullable

public interface LocalDateTimeFieldColumnNotNull
public interface LocalDateTimeFieldColumnNullable

public interface KotlinxLocalDateTimeFieldColumnNotNull
public interface KotlinxLocalDateTimeFieldColumnNullable

public interface LocalDateFieldColumnNotNull
public interface LocalDateFieldColumnNullable

public interface KotlinxLocalDateFieldColumnNotNull
public interface KotlinxLocalDateFieldColumnNullable

public interface OffsetDateTimeFieldColumnNotNull
public interface OffsetDateTimeFieldColumnNullable

public interface LocalTimeFieldColumnNotNull
public interface LocalTimeFieldColumnNullable

public interface BooleanFieldColumnNotNull

public interface IntFieldColumnNotNull
public interface IntFieldColumnNullable

public interface UuidFieldColumnNotNull
public interface UuidFieldColumnNullable
